name: cosmetics_shop_analytics
version: "1.0.0"

profile: cosmetics_shop_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  cosmetics_shop_analytics:
    raw:
      +materialized: view
      +schema: raw
    stg:
      +materialized: view
      +schema: stg
    dwh:
      +materialized: table
      +schema: dwh
